version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/codeigniter.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - codeigniter-net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - codeigniter-net

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "./data/:/docker-entrypoint-initdb.d/"
    networks:
      - codeigniter-net

networks:
  codeigniter-net:
    driver: bridge
