version: '3'
services:
  app:
    image: thecodingmachine/php:7.4-v4-apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "${APP_PORT}:80"
    environment:
      APACHE_DOCUMENT_ROOT: "/"
      APACHE_DIRECTORY_INDEX: index.php
      PHP_EXTENSION_INTL: 1

  db:
    image: bitnami/mariadb:10.3-debian-10
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "./sample_data/:/docker-entrypoint-initdb.d/"
